# Copyright 2026 Google LLC
# SPDX-License-Identifier: Apache-2.0
packages:
  - '.'
  - 'web'

allowBuilds:
  "@parcel/watcher": true
  esbuild: true
  keytar: true
  ttf2woff2: false
  "@vscode/vsce-sign": true

minimumReleaseAgeExclude:
  - '@pierre/diffs@1.5.0'
