[aliases]
sync = ["util", "exec", "--", "sh", "-c", "jj git fetch && jj rebase -s 'roots(mutable())' -d main --skip-emptied && jj log"]
upload = ["util", "exec", "--", "pnpm", "exec", "ts-node", "tooling/jj/upload.ts"]

[fix.tools.prettier]
command = ["pnpm", "exec", "prettier", "--stdin-filepath", "$path"]
patterns = [
    "glob:'**/*.ts'",
    "glob:'**/*.tsx'",
    "glob:'**/*.js'",
    "glob:'**/*.jsx'",
    "glob:'**/*.json'",
    "glob:'**/*.md'",
    "glob:'**/*.css'",
]

[fix.tools.addlicense]
command = ["go", "run", "github.com/google/addlicense@v1.1.1", "-s=only", "$path"]
patterns = [
    "glob:'**/*.ts'",
    "glob:'**/*.tsx'",
    "glob:'**/*.js'",
    "glob:'**/*.jsx'",
    "glob:'**/*.css'",
]


[[--scope]]
--when.environments = ["ANTIGRAVITY_AGENT"]
[--scope.ui]
paginate = "never"

[snapshot]
auto-update-stale = true

[templates]
git_push_bookmark = "'up-' ++ change_id.shortest(3)"