/**
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * GENERATED FILE - DO NOT EDIT MANUALLY.
 * Generated by tooling/generate-settings-schema.ts from package.json contributes.configuration.
 */

export interface SettingDefinition {
    readonly key: string;
    readonly title: string;
    readonly description: string;
    readonly category: string;
    readonly type: 'string' | 'number' | 'boolean' | 'array';
    readonly default: unknown;
    readonly enum?: readonly (string | number | boolean)[];
    readonly enumDescriptions?: readonly string[];
}

export const PACKAGE_SETTINGS: readonly SettingDefinition[] = [
    {
        key: 'refreshDebounceMillis',
        title: 'Refresh Debounce Millis',
        description: 'Base debounce time (ms) for SCM refresh based on file events.',
        category: 'General',
        type: 'number',
        default: 100,
    },
    {
        key: 'readTimeoutSeconds',
        title: 'Read Timeout Seconds',
        description: 'Timeout in seconds for read operations executed by the jj service.',
        category: 'General',
        type: 'number',
        default: 120,
    },
    {
        key: 'showProcessMonitorPanel',
        title: 'Show Process Monitor Panel',
        description: 'Controls whether the JJ Process Monitor diagnostic view is displayed in the bottom panel.',
        category: 'General',
        type: 'boolean',
        default: false,
    },
    {
        key: 'refreshDebounceMaxMultiplier',
        title: 'Refresh Debounce Max Multiplier',
        description: 'Maximum multiplier for the debounce timeout when events continue to occur.',
        category: 'General',
        type: 'number',
        default: 4,
    },
    {
        key: 'fileWatcherMode',
        title: 'File Watcher Mode',
        description: 'Controls how the extension detects external file changes.',
        category: 'General',
        type: 'string',
        default: 'polling',
        enum: ['polling', 'watch'],
        enumDescriptions: [
            'Use periodic status checks (default).',
            'Use a file watcher (parcel-watcher) for efficient updates (only on changes).',
        ],
    },
    {
        key: 'codeForge.provider',
        title: 'Code Forge Provider',
        description:
            'Force the active Code Forge provider to a specific service. If not set, it is auto-detected from git remotes.',
        category: 'General',
        type: 'string',
        default: '',
        enum: ['github', 'gitlab', 'gerrit'],
    },
    {
        key: 'codeForge.pollIntervalSeconds',
        title: 'Code Forge Poll Interval Seconds',
        description:
            'How often (in seconds) to re-fetch pull request, merge request and review status from the code forge (GitHub, GitLab or Gerrit) while the window is focused. Set to 0 to disable background polling. Positive values below 10 are treated as 10.',
        category: 'Performance',
        type: 'number',
        default: 60,
    },
    {
        key: 'codeForge.minRefreshIntervalSeconds',
        title: 'Code Forge Min Refresh Interval Seconds',
        description:
            "Minimum time (in seconds) between code forge status fetches that are prompted by local repository changes or the window regaining focus, such as file edits and jj operations. Changes that arrive inside the window are fetched once, when it ends. Raise this to reduce API usage, for example to stay under GitHub's rate limit. Background polling, uploads and manual refreshes are not throttled. 0 disables throttling.",
        category: 'Performance',
        type: 'number',
        default: 0,
    },
    {
        key: 'gerrit.host',
        title: 'Gerrit Host',
        description:
            'Gerrit host URL (e.g., https://gerrit-review.googlesource.com). If not set, extension attempts to detect it from .gitreview or git remotes.',
        category: 'General',
        type: 'string',
        default: '',
    },
    {
        key: 'gerrit.project',
        title: 'Gerrit Project',
        description: 'Gerrit project name. If not set, extension attempts to detect it from git remotes.',
        category: 'General',
        type: 'string',
        default: '',
    },
    {
        key: 'gitlab.host',
        title: 'Gitlab Host',
        description:
            'GitLab host URL (e.g., https://gitlab.com). If not set, extension attempts to detect it from git remotes.',
        category: 'General',
        type: 'string',
        default: '',
    },
    {
        key: 'alwaysUploadStack',
        title: 'Always Upload Stack',
        description:
            "Always upload changes as stacked pull requests or merge requests. When enabled, the extra 'Upload Stack' context menu item is hidden and all upload actions upload the full stack.",
        category: 'General',
        type: 'boolean',
        default: false,
    },
    {
        key: 'uploadCommand',
        title: 'Upload Command',
        description:
            "Custom command to run for upload. Example: 'git push'. The command will be prefixed with 'jj' and suffixed with '-r <revision>' or repeated '-r'/'-c' arguments for stacked uploads.",
        category: 'General',
        type: 'string',
        default: '',
    },
    {
        key: 'minChangeIdLength',
        title: 'Min Change Id Length',
        description:
            'Minimum number of characters to display for change IDs. This affects the unique prefix calculation and UI truncation.',
        category: 'Log Graph',
        type: 'number',
        default: 1,
    },
    {
        key: 'maxMutableAncestors',
        title: 'Max Mutable Ancestors',
        description: 'Maximum number of mutable ancestors to display in the SCM view.',
        category: 'General',
        type: 'number',
        default: 10,
    },
    {
        key: 'logTheme',
        title: 'Log Theme',
        description: 'Color theme for the graph lanes in the JJ Log view.',
        category: 'Log Graph',
        type: 'string',
        default: 'default',
        enum: [
            'default',
            'oceanic',
            'sunset',
            'neon',
            'pastel',
            'monochrome',
            'nord',
            'dracula',
            'forest',
            'solarized',
            'autumn',
            'matrix',
        ],
    },
    {
        key: 'graphLabelAlignment',
        title: 'Graph Label Alignment',
        description: 'Controls the horizontal alignment of commit messages in the log view.',
        category: 'Log Graph',
        type: 'string',
        default: 'aligned',
        enum: ['aligned', 'compact'],
        enumDescriptions: [
            'Keep commit messages aligned in a single column.',
            'Place commit messages immediately to the right of their node.',
        ],
    },
    {
        key: 'commit.titleWidthRuler',
        title: 'Commit Title Width Ruler',
        description: 'Width at which to display a ruler in the commit details description editor for the title line.',
        category: 'Commit Editor',
        type: 'number',
        default: 50,
    },
    {
        key: 'commit.bodyWidthRuler',
        title: 'Commit Body Width Ruler',
        description: 'Width at which to display a ruler in the commit details description editor for the body.',
        category: 'Commit Editor',
        type: 'number',
        default: 72,
    },
    {
        key: 'commit.formatDescriptionOnSave',
        title: 'Commit Format Description On Save',
        description: 'Automatically format and wrap the commit description body when saving.',
        category: 'Commit Editor',
        type: 'boolean',
        default: false,
    },
    {
        key: 'suppressGitColocationWarning',
        title: 'Suppress Git Colocation Warning',
        description: 'Suppress the warning to disable the built-in Git extension in colocated repositories.',
        category: 'General',
        type: 'boolean',
        default: false,
    },
    {
        key: 'binaryPath',
        title: 'Binary Path',
        description:
            "Optional absolute path to the 'jj' binary. If empty, the extension will search for it in your PATH.",
        category: 'General',
        type: 'string',
        default: '',
    },
    {
        key: 'workspacesLocation',
        title: 'Workspaces Location',
        description:
            'Directory where new workspaces are created. Relative paths are resolved against the main repository root.',
        category: 'Repositories',
        type: 'string',
        default: '.workspaces',
    },
    {
        key: 'openDiffOnClick',
        title: 'Open Diff On Click',
        description:
            'Controls whether the diff editor should be opened when clicking a change. Otherwise the regular editor will be opened.',
        category: 'Diff Viewer',
        type: 'boolean',
        default: true,
    },
    {
        key: 'autoRepositoryDetection',
        title: 'Auto Repository Detection',
        description:
            'Controls whether to automatically detect jj repositories. true: Scans workspace folders and all subfolders recursively; false: Only checks workspace roots; subFolders: Scans immediate subfolders; openEditors: Only registers on-demand when files are opened.',
        category: 'Repositories',
        type: 'boolean',
        default: true,
        enum: [true, false, 'subFolders', 'openEditors'],
    },
    {
        key: 'scanRepositories',
        title: 'Scan Repositories',
        description: 'List of absolute or workspace-relative directory paths to explicitly scan for jj repositories.',
        category: 'Repositories',
        type: 'array',
        default: [],
    },
    {
        key: 'ignoredRepositories',
        title: 'Ignored Repositories',
        description: 'List of absolute directory paths of jj repositories that should be explicitly ignored.',
        category: 'Repositories',
        type: 'array',
        default: [],
    },
] as const;
