/**
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 */

import * as cp from 'node:child_process';
import * as fs from 'node:fs';
import * as path from 'node:path';

interface PropertySchema {
    type?: string | string[];
    default?: unknown;
    description?: string;
    enum?: unknown[];
    enumDescriptions?: string[];
}

interface PackageJson {
    contributes?: {
        configuration?: {
            properties?: Record<string, PropertySchema>;
        };
    };
}

function deriveTitle(key: string): string {
    const raw = key.replace(/^jj-view\./, '');
    const parts = raw.split(/[._-]/);
    return parts
        .map((p) => p.replace(/([A-Z])/g, ' $1').trim())
        .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
        .join(' ');
}

function deriveCategory(key: string): string {
    const norm = key.replace(/^jj-view\./, '');
    if (norm.startsWith('commit.')) {
        return 'Commit Editor';
    }
    if (norm.includes('graph') || norm.includes('logTheme') || norm.includes('minChangeIdLength')) {
        return 'Log Graph';
    }
    if (norm.includes('diff') || norm.includes('Diff')) {
        return 'Diff Viewer';
    }
    if (norm.includes('Repositories') || norm.includes('Repository') || norm.includes('workspaces')) {
        return 'Repositories';
    }
    if (norm.includes('watcher') || norm.includes('timeout') || norm.includes('poll') || norm.includes('minRefresh')) {
        return 'Performance';
    }
    return 'General';
}

function normalizeType(type?: string | string[]): 'string' | 'number' | 'boolean' | 'array' {
    if (Array.isArray(type)) {
        if (type.includes('boolean')) {
            return 'boolean';
        }
        if (type.includes('number')) {
            return 'number';
        }
        return 'string';
    }
    if (type === 'boolean' || type === 'number' || type === 'array') {
        return type;
    }
    return 'string';
}

function main(): void {
    const rootDir = process.cwd();
    const packageJsonPath = path.join(rootDir, 'package.json');
    const outputPath = path.join(rootDir, 'web', 'src', 'settings', 'package-settings.generated.ts');

    const pkg = JSON.parse(fs.readFileSync(packageJsonPath, 'utf8')) as PackageJson;
    const props = pkg.contributes?.configuration?.properties ?? {};

    const definitions = Object.entries(props).map(([fullKey, schema]) => {
        const key = fullKey.replace(/^jj-view\./, '');
        const title = deriveTitle(key);
        const category = deriveCategory(key);
        const type = normalizeType(schema.type);
        const description = schema.description ?? '';
        const defaultValue = schema.default ?? (type === 'boolean' ? false : type === 'number' ? 0 : '');

        return {
            key,
            title,
            description,
            category,
            type,
            default: defaultValue,
            enum: schema.enum,
            enumDescriptions: schema.enumDescriptions,
        };
    });

    const fileContent = `/**
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * GENERATED FILE - DO NOT EDIT MANUALLY.
 * Generated by tooling/generate-settings-schema.ts from package.json contributes.configuration.
 */

export interface SettingDefinition {
    readonly key: string;
    readonly title: string;
    readonly description: string;
    readonly category: string;
    readonly type: 'string' | 'number' | 'boolean' | 'array';
    readonly default: unknown;
    readonly enum?: readonly (string | number | boolean)[];
    readonly enumDescriptions?: readonly string[];
}

export const PACKAGE_SETTINGS: readonly SettingDefinition[] = ${JSON.stringify(definitions, null, 4)} as const;
`;

    fs.mkdirSync(path.dirname(outputPath), { recursive: true });
    fs.writeFileSync(outputPath, fileContent, 'utf8');

    const biomeBin = path.join(rootDir, 'node_modules', '.bin', 'biome');
    if (fs.existsSync(biomeBin)) {
        try {
            cp.execFileSync(biomeBin, ['check', '--write', outputPath], { stdio: 'ignore' });
        } catch {
            // Ignore format errors if biome fails
        }
    }
    console.log(`Generated settings schema with ${definitions.length} settings to ${outputPath}`);
}

main();
