name: License

on:
    push:
        branches: ['main']
    pull_request:
        branches: ['main']

concurrency:
    group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
    cancel-in-progress: true

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            PNPM_CONFIG_VERIFY_DEPS_BEFORE_RUN: 'false'

        steps:
            - uses: actions/checkout@v7

            - name: Install pnpm
              uses: pnpm/setup@v2
              with:
                  version: 11
                  install: false

            - name: Cache Go build & modules
              uses: actions/cache@v6
              with:
                  path: |
                      ~/.cache/go-build
                      ~/go/pkg/mod
                  key: go-license-${{ runner.os }}-v1.1.1
                  restore-keys: |
                      go-license-${{ runner.os }}-

            - name: Check License
              run: pnpm check-license
